# Generated by Django 4.2.25 on 2025-10-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aiconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('category', models.CharField(choices=[('racao', 'Ração'), ('petisco', 'Petisco'), ('brinquedo', 'Brinquedo'), ('acessorio', 'Acessório'), ('higiene', 'Higiene'), ('saude', 'Saúde')], max_length=20, verbose_name='Categoria')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('stock', models.IntegerField(default=0, verbose_name='Estoque')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('target_species', models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('passaro', 'Pássaro'), ('peixe', 'Peixe'), ('roedor', 'Roedor'), ('todos', 'Todos')], max_length=20, verbose_name='Espécie')),
                ('target_breed', models.CharField(blank=True, max_length=100, verbose_name='Raça Específica')),
                ('target_age', models.CharField(choices=[('filhote', 'Filhote'), ('adulto', 'Adulto'), ('idoso', 'Idoso'), ('todos', 'Todos')], default='todos', max_length=20, verbose_name='Idade')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
    ]
